pushd %~dp0
rrdtool graph .\MI17W.png -a PNG -w 785 -h 151 --start end-1w -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%"  DEF:MI17=.\License.rrd:MI17:MAX CDEF:CMI17=MI17,UN,PREV,MI17,IF LINE3:CMI17#35b73d:"License Usage MapInfo 17" GPRINT:MI17:LAST:"Cur\: %%2.0lf" GPRINT:MI17:MAX:"Max\: %%2.0lf" GPRINT:MI17:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\MI17M.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%"  DEF:MI17=.\License.rrd:MI17:MAX CDEF:CMI17=MI17,UN,PREV,MI17,IF LINE3:CMI17#35b73d:"License Usage MapInfo 17" GPRINT:MI17:LAST:"Cur\: %%2.0lf" GPRINT:MI17:MAX:"Max\: %%2.0lf" GPRINT:MI17:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\FMEW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:3 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:FME=.\LicenseFME.rrd:FME:MAX CDEF:CFME=FME,UN,PREV,FME,IF AREA:CFME#35b73d:"License Usage FME" GPRINT:FME:LAST:"Cur\: %%2.0lf" GPRINT:FME:MAX:"Max\: %%2.0lf" GPRINT:FME:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\FMEM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:3 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:FME=.\LicenseFME.rrd:FME:MAX CDEF:CFME=FME,UN,PREV,FME,IF AREA:CFME#35b73d:"License Usage FME" GPRINT:FME:LAST:"Cur\: %%2.0lf" GPRINT:FME:MAX:"Max\: %%2.0lf" GPRINT:FME:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\FME.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:3 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:FME=.\LicenseFME.rrd:FME:MAX CDEF:CFME=FME,UN,PREV,FME,IF LINE2:CFME#35b73d:"License Usage FME" GPRINT:FME:LAST:"Cur\: %%2.0lf" GPRINT:FME:MAX:"Max\: %%2.0lf" GPRINT:FME:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\WI.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:5 -u 20 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:WI=.\LicenseWI.rrd:WI:MAX CDEF:CWI=WI,UN,PREV,WI,IF LINE2:CWI#35b73d:"License Usage WI" GPRINT:WI:LAST:"Cur\: %%2.0lf" GPRINT:WI:MAX:"Max\: %%2.0lf" GPRINT:WI:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\WIM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:5 -u 20 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:WI=.\LicenseWI.rrd:WI:MAX CDEF:CWI=WI,UN,PREV,WI,IF LINE2:CWI#35b73d:"License Usage WI" GPRINT:WI:LAST:"Cur\: %%2.0lf" GPRINT:WI:MAX:"Max\: %%2.0lf" GPRINT:WI:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t" 

rrdtool graph .\MC.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:5 -u 20 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMC.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MCW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:5 -u 20 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMC.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MCM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:5 -u 20 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMC.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MCY.png -a PNG -w 785 -h 151 --start end-1y -y 1:5 -u 20 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMC.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\RCD.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:3 -u 9 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RCD=.\LicenseRCD.rrd:RCD:MAX CDEF:CRCD=RCD,UN,PREV,RCD,IF LINE2:CRCD#35b73d:"License Usage Sofistik Reinf. Detailing" GPRINT:RCD:LAST:"Cur\: %%2.0lf" GPRINT:RCD:MAX:"Max\: %%2.0lf" GPRINT:RCD:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\RCDW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:3 -u 9 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RCD=.\LicenseRCD.rrd:RCD:MAX CDEF:CRCD=RCD,UN,PREV,RCD,IF LINE2:CRCD#35b73d:"License Usage Sofistik Reinf. Detailing" GPRINT:RCD:LAST:"Cur\: %%2.0lf" GPRINT:RCD:MAX:"Max\: %%2.0lf" GPRINT:RCD:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\RCDM.png -a PNG -w 785 -h 151 --start end-5d end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:3 -u 9 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RCD=.\LicenseRCD.rrd:RCD:MAX CDEF:CRCD=RCD,UN,PREV,RCD,IF LINE2:CRCD#35b73d:"License Usage Sofistik Reinf. Detailing" GPRINT:RCD:LAST:"Cur\: %%2.0lf" GPRINT:RCD:MAX:"Max\: %%2.0lf" GPRINT:RCD:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\RCDY.png -a PNG -w 785 -h 151 --start end-1y -y 1:3 -u 9 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RCD=.\LicenseRCD.rrd:RCD:MAX CDEF:CRCD=RCD,UN,PREV,RCD,IF LINE2:CRCD#35b73d:"License Usage Sofistik Reinf. Detailing" GPRINT:RCD:LAST:"Cur\: %%2.0lf" GPRINT:RCD:MAX:"Max\: %%2.0lf" GPRINT:RCD:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\GSLP.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:GSLP=.\LicenseGSLP.rrd:GSLP:MAX CDEF:CGSLP=GSLP,UN,PREV,GSLP,IF LINE2:CGSLP#35b73d:"License Usage GSLP" GPRINT:GSLP:LAST:"Cur\: %%2.0lf" GPRINT:GSLP:MAX:"Max\: %%2.0lf" GPRINT:GSLP:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\GSLPW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:GSLP=.\LicenseGSLP.rrd:GSLP:MAX CDEF:CGSLP=GSLP,UN,PREV,GSLP,IF LINE2:CGSLP#35b73d:"License Usage GSLP" GPRINT:GSLP:LAST:"Cur\: %%2.0lf" GPRINT:GSLP:MAX:"Max\: %%2.0lf" GPRINT:GSLP:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\GSLPM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:GSLP=.\LicenseGSLP.rrd:GSLP:MAX CDEF:CGSLP=GSLP,UN,PREV,GSLP,IF LINE2:CGSLP#35b73d:"License Usage GSLP" GPRINT:GSLP:LAST:"Cur\: %%2.0lf" GPRINT:GSLP:MAX:"Max\: %%2.0lf" GPRINT:GSLP:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\GSLPY.png -a PNG -w 785 -h 151 --start end-1y -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:GSLP=.\LicenseGSLP.rrd:GSLP:MAX CDEF:CGSLP=GSLP,UN,PREV,GSLP,IF LINE2:CGSLP#35b73d:"License Usage GSLP" GPRINT:GSLP:LAST:"Cur\: %%2.0lf" GPRINT:GSLP:MAX:"Max\: %%2.0lf" GPRINT:GSLP:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\RSK.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:1 -u 4 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RSK=.\LicenseRSK.rrd:RSK:MAX CDEF:CRSK=RSK,UN,PREV,RSK,IF LINE2:CRSK#35b73d:"License Usage @RISK 8.0" GPRINT:RSK:LAST:"Cur\: %%2.0lf" GPRINT:RSK:MAX:"Max\: %%2.0lf" GPRINT:RSK:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\RSKM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:1 -u 4 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RSK=.\LicenseRSK.rrd:RSK:MAX CDEF:CRSK=RSK,UN,PREV,RSK,IF LINE2:CRSK#35b73d:"License Usage @RISK 8.0" GPRINT:RSK:LAST:"Cur\: %%2.0lf" GPRINT:RSK:MAX:"Max\: %%2.0lf" GPRINT:RSK:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\RSKW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:1 -u 4 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RSK=.\LicenseRSK.rrd:RSK:MAX CDEF:CRSK=RSK,UN,PREV,RSK,IF LINE2:CRSK#35b73d:"License Usage @RISK 8.0" GPRINT:RSK:LAST:"Cur\: %%2.0lf" GPRINT:RSK:MAX:"Max\: %%2.0lf" GPRINT:RSK:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MCUS.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:5 -u 37 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMCUS.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MCUSW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:5 -u 37 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMCUS.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MCUSM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:5 -u 37 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMCUS.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MCUSY.png -a PNG -w 785 -h 151 --start end-1y  -y 1:5 -u 37 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MC=.\LicenseMCUS.rrd:MC:MAX CDEF:CMC=MC,UN,PREV,MC,IF LINE2:CMC#35b73d:"License Usage MC" GPRINT:MC:LAST:"Cur\: %%2.0lf" GPRINT:MC:MAX:"Max\: %%2.0lf" GPRINT:MC:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\RSKY.png -a PNG -w 785 -h 151 --start end-1y  -y 1:1 -u 4 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RSK=.\LicenseRSK.rrd:RSK:MAX CDEF:CRSK=RSK,UN,PREV,RSK,IF LINE2:CRSK#35b73d:"License Usage @RISK 8.0" GPRINT:RSK:LAST:"Cur\: %%2.0lf" GPRINT:RSK:MAX:"Max\: %%2.0lf" GPRINT:RSK:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\FMEY.png -a PNG -w 785 -h 151 --start end-1y  -y 1:3 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:FME=.\LicenseFME.rrd:FME:MAX CDEF:CFME=FME,UN,PREV,FME,IF AREA:CFME#35b73d:"License Usage FME" GPRINT:FME:LAST:"Cur\: %%2.0lf" GPRINT:FME:MAX:"Max\: %%2.0lf" GPRINT:FME:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MI17Y.png -a PNG -w 785 -h 151 --start end-1y  -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%"  DEF:MI17=.\License.rrd:MI17:MAX CDEF:CMI17=MI17,UN,PREV,MI17,IF LINE3:CMI17#35b73d:"License Usage MapInfo 17" GPRINT:MI17:LAST:"Cur\: %%2.0lf" GPRINT:MI17:MAX:"Max\: %%2.0lf" GPRINT:MI17:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\DSP.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:DSP=.\LicenseDSP.rrd:DSP:MAX CDEF:CDSP=DSP,UN,PREV,DSP,IF LINE2:CDSP#35b73d:"License Usage DSP" GPRINT:DSP:LAST:"Cur\: %%2.0lf" GPRINT:DSP:MAX:"Max\: %%2.0lf" GPRINT:DSP:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\DSPW.png -a PNG -w 785 -h 151 --start end-1w -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:DSP=.\LicenseDSP.rrd:DSP:MAX CDEF:CDSP=DSP,UN,PREV,DSP,IF LINE2:CDSP#35b73d:"License Usage DSP" GPRINT:DSP:LAST:"Cur\: %%2.0lf" GPRINT:DSP:MAX:"Max\: %%2.0lf" GPRINT:DSP:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MLB.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MLB=.\LicenseMLB.rrd:MLB:MAX CDEF:CMLB=MLB,UN,PREV,MLB,IF LINE2:CMLB#35b73d:"License Usage MLB" GPRINT:MLB:LAST:"Cur\: %%2.0lf" GPRINT:MLB:MAX:"Max\: %%2.0lf" GPRINT:MLB:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MLBW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MLB=.\LicenseMLB.rrd:MLB:MAX CDEF:CMLB=MLB,UN,PREV,MLB,IF LINE2:CMLB#35b73d:"License Usage MLB" GPRINT:MLB:LAST:"Cur\: %%2.0lf" GPRINT:MLB:MAX:"Max\: %%2.0lf" GPRINT:MLB:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\MLBM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:MLB=.\LicenseMLB.rrd:MLB:MAX CDEF:CMLB=MLB,UN,PREV,MLB,IF LINE2:CMLB#35b73d:"License Usage MLB" GPRINT:MLB:LAST:"Cur\: %%2.0lf" GPRINT:MLB:MAX:"Max\: %%2.0lf" GPRINT:MLB:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\DIAM.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:DIAM=.\LicenseDIAM.rrd:DIAM:MAX CDEF:CDIAM=DIAM,UN,PREV,DIAM,IF LINE2:CDIAM#35b73d:"License Usage DIAM" GPRINT:DIAM:LAST:"Cur\: %%2.0lf" GPRINT:DIAM:MAX:"Max\: %%2.0lf" GPRINT:DIAM:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\DIAMW.png -a PNG -w 785 -h 151 --start end-1w -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:DIAM=.\LicenseDIAM.rrd:DIAM:MAX CDEF:CDIAM=DIAM,UN,PREV,DIAM,IF LINE2:CDIAM#35b73d:"License Usage DIAM" GPRINT:DIAM:LAST:"Cur\: %%2.0lf" GPRINT:DIAM:MAX:"Max\: %%2.0lf" GPRINT:DIAM:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\DIAMM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:5 -u 15 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:DIAM=.\LicenseDIAM.rrd:DIAM:MAX CDEF:CDIAM=DIAM,UN,PREV,DIAM,IF LINE2:CDIAM#35b73d:"License Usage DIAM" GPRINT:DIAM:LAST:"Cur\: %%2.0lf" GPRINT:DIAM:MAX:"Max\: %%2.0lf" GPRINT:DIAM:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t\t"

rrdtool graph .\VISU_USW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:1 -u 6 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:VISU=.\LicenseVISU.rrd:VISU:MAX CDEF:CVISU=VISU,UN,PREV,VISU,IF LINE2:CVISU#35b73d:"License Usage VISUM US" GPRINT:VISU:LAST:"Cur\: %%2.0lf" GPRINT:VISU:MAX:"Max\: %%2.0lf" GPRINT:VISU:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\VISSIM_USW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:1 -u 6 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:VISSI=.\LicenseVISSI.rrd:VISSI:MAX CDEF:CVISSI=VISSI,UN,PREV,VISSI,IF LINE2:CVISSI#35b73d:"License Usage VISSIM US" GPRINT:VISSI:LAST:"Cur\: %%2.0lf" GPRINT:VISSI:MAX:"Max\: %%2.0lf" GPRINT:VISSI:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\VISU_USM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:1 -u 6 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:VISU=.\LicenseVISU.rrd:VISU:MAX CDEF:CVISU=VISU,UN,PREV,VISU,IF LINE2:CVISU#35b73d:"License Usage VISUM US" GPRINT:VISU:LAST:"Cur\: %%2.0lf" GPRINT:VISU:MAX:"Max\: %%2.0lf" GPRINT:VISU:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\VISSIM_USM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:1 -u 6 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:VISSI=.\LicenseVISSI.rrd:VISSI:MAX CDEF:CVISSI=VISSI,UN,PREV,VISSI,IF LINE2:CVISSI#35b73d:"License Usage VISSIM US" GPRINT:VISSI:LAST:"Cur\: %%2.0lf" GPRINT:VISSI:MAX:"Max\: %%2.0lf" GPRINT:VISSI:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t\t\t"

rrdtool graph .\GLMAP_US.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:1 -u 7 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:GMUS=.\LicenseGMUS.rrd:GMUS:MAX CDEF:CGMUS=GMUS,UN,PREV,GMUS,IF LINE2:CGMUS#35b73d:"License Usage GL MAP US" GPRINT:GMUS:LAST:"Cur\: %%2.0lf" GPRINT:GMUS:MAX:"Max\: %%2.0lf" GPRINT:GMUS:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\GLMAP_USW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:1 -u 7 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:GMUS=.\LicenseGMUS.rrd:GMUS:MAX CDEF:CGMUS=GMUS,UN,PREV,GMUS,IF LINE2:CGMUS#35b73d:"License Usage GL MAP US" GPRINT:GMUS:LAST:"Cur\: %%2.0lf" GPRINT:GMUS:MAX:"Max\: %%2.0lf" GPRINT:GMUS:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\GLMAP_EUW.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:1 -u 7 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:GMEU=.\LicenseGMEU.rrd:GMEU:MAX CDEF:CGMEU=GMEU,UN,PREV,GMEU,IF LINE2:CGMEU#35b73d:"License Usage GL MAP EU" GPRINT:GMEU:LAST:"Cur\: %%2.0lf" GPRINT:GMEU:MAX:"Max\: %%2.0lf" GPRINT:GMEU:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\PD3D_W.png -a PNG -w 785 -h 151 --start end-5d -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:1 -u 4 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:PD3D=.\LicensePD3D.rrd:PD3D:MAX CDEF:CPD3D=PD3D,UN,PREV,PD3D,IF LINE2:CPD3D#35b73d:"License Usage PD 3D" GPRINT:PD3D:LAST:"Cur\: %%2.0lf" GPRINT:PD3D:MAX:"Max\: %%2.0lf" GPRINT:PD3D:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\RHN.png -a PNG -w 785 -h 151 --start end-24h -x HOUR:1:HOUR:1:HOUR:2:0:%%R -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RHN=.\LicenseRHN.rrd:RHN:MAX CDEF:CRHN=RHN,UN,PREV,RHN,IF LINE2:CRHN#35b73d:"License Usage Rhino" GPRINT:RHN:LAST:"Cur\: %%2.0lf" GPRINT:RHN:MAX:"Max\: %%2.0lf" GPRINT:RHN:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\RHNW.png -a PNG -w 785 -h 151 --start end-1w -x HOUR:8:DAY:1:DAY:1:0:"%%a %%R" -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RHN=.\LicenseRHN.rrd:RHN:MAX CDEF:CRHN=RHN,UN,PREV,RHN,IF LINE2:CRHN#35b73d:"License Usage Rhino" GPRINT:RHN:LAST:"Cur\: %%2.0lf" GPRINT:RHN:MAX:"Max\: %%2.0lf" GPRINT:RHN:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

rrdtool graph .\RHNM.png -a PNG -w 785 -h 151 --start end-1m -x DAY:1:DAY:5:DAY:5:86400:"%%d/%%m" -y 1:2 -u 10 -l 0  -v "License Usage" --title "License Utilization" --font WATERMARK:8 -W "%DATE% %TIME%" DEF:RHN=.\LicenseRHN.rrd:RHN:MAX CDEF:CRHN=RHN,UN,PREV,RHN,IF LINE2:CRHN#35b73d:"License Usage Rhino" GPRINT:RHN:LAST:"Cur\: %%2.0lf" GPRINT:RHN:MAX:"Max\: %%2.0lf" GPRINT:RHN:MIN:"Min\: %%2.0lf\t\t\t\t\t\t\t"

popd